datawarehouse:
  target: prod
  outputs:
    prod:
      type: postgres
      host: "{{ env_var('DB_HOST') }}"
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASS') }}"
      port: "{{ env_var('DB_PORT') |int }}"
      dbname: "{{ env_var('DB_NAME') }}"
      schema: "{{ env_var('DB_SCHEMA') }}"
      threads: "{{ env_var('DB_THREADS') | int }}"
      type: "{{ env_var('DB_TYPE') }}"
      keepalives_idle: 0
  target: prod
