version: 2

models:
  - name: dbsales1
    schema: public
    tables:
      - name: dm_commodities
        description: "Datamart para os dados de commodities integrados"
        columns:
          - name: data
            description: "Data de observação"
          - name: simbolo
            description: "Simbolo do commodity"
          - name: valor_fechamento
            description: "Valor de fechamento do commodity"
          - name: acao
            description: "Tipo de transação realizada"
          - name: quantidade
            description: "Quantidade transacionada"
          - name: valor
            description: "Valor da transação"
          - name: ganho
            description: "Perca ou ganho da transação"
     